CC = gcc
CFLAGS = -Wall -Werror -Wextra -pedantic

todo_api_0: task4.o socketlib.o
	$(CC) $(CFLAGS) -o todo_api_0 task4.o socketlib.o

task4.o: task4.c socketlib.h
	$(CC) $(CFLAGS) -c task4.c

todo_api_1: task5.o socketlib.o
	$(CC) $(CFLAGS) -o todo_api_1 task5.o socketlib.o

task5.o: task5.c socketlib.h
	$(CC) $(CFLAGS) -c task5.c

todo_api_2: task6.o socketlib.o
	$(CC) $(CFLAGS) -o todo_api_2 task6.o socketlib.o

task6.o: task6.c socketlib.h
	$(CC) $(CFLAGS) -c task6.c

todo_api_3: task7.o socketlib.o
	$(CC) $(CFLAGS) -o todo_api_3 task7.o socketlib.o

task7.o: task7.c socketlib.h
	$(CC) $(CFLAGS) -c task7.c

todo_api_4: task8.o socketlib.o
	$(CC) $(CFLAGS) -o todo_api_4 task8.o socketlib.o

task8.o: task8.c socketlib.h
	$(CC) $(CFLAGS) -c task8.c

todo_api_5: task9.o socketlib.o
	$(CC) $(CFLAGS) -o todo_api_5 task9.o socketlib.o

task9.o: task9.c socketlib.h
	$(CC) $(CFLAGS) -c task9.c
